### ISSUE TITLE
Loadout Bindings

### ISSUE THREAD

**Issue by Pokettz1** [nikkisaurus/LoadoutBindings#1]
Hi, just reporting in on Loadout Bindings addon for WoW. Since the pre-patch for The War Within went live and the Hero Talent Tree interface was added. I can no longer access any configuration options for Loadout Bindings via the talent window. Hoping to see an update soon. Thank you for this addon, it has been very helpful this past expansion.

**Comment by nikkisaurus** [comment]
Do you notice any Lua errors or is it just missing?

**Comment by Pokettz1** [comment]
![WoWScrnShot_072924_215239](https://github.com/user-attachments/assets/f8d42ce5-ef57-4378-98d6-f9dc94e46070)


No Lua that I have seen, you can see on the screenshot here that Hero talents is where the Loadout bindings drop box used to be. The bindings tab at the bottom of the talent window is also missing.

**Comment by Pokettz1** [comment]
I have disabled every addon I have except for LB and it still doesn't show up. I am no expert but I think it has to do with the Hero Talent interface/Spellbook being added to the Talent Window. I am hoping it's something that can be worked around. Thanks again for taking the time to respond. I appreciate it and left a donation to you. Not much but it's something.

**Comment by nikkisaurus** [comment]
Thank you. 

I've been out of the game since like September of last year but I had pre-ordered the expansion and was planning on getting back in.

It should probably be a simple fix, because this addon itself isn't really large or complicated, as I never got the time to flesh it out much more. This week may be a little busy for me as I have several commitments I need to work on, but I'll try to find time to pop in and take a look as soon as I can, especially if it's something that will be a quick fix.

I've been out of the loop with what's going on with the game as well; are the hero talents a max level thing? Are they something just added in or do I need to do some stuff to unlock it?

Worst case scenario I can just do a separate interface instead of directly attaching it.

**Comment by Pokettz1** [comment]
Ah the game is looking to be pretty fun going forward. I appreciate that you're busy, honestly it makes me feel better just to know you'll take a look. It's not a game breaking thing but it's just such a great QoL upgrade you've provided.

Hero Talents are one of the new features for the xpac. Each class has one tree per spec but a choice of two.

Eg. Hunters have Sentinel, Pack Leader and Dark Ranger. So Sentinel is available to MM and Surv. Pack leader is Surv and BM, Dark Ranger is BM and MM. So each spec can choose one of two. Starting at level 71 you choose which tree you'd like and can add a talent point each level up to 80. You can freely swap and change. Some trees are more passive with what they offer and some might empower an existing talent or offer a new one entirely. You can check out each of the Hero Trees on sites like Wowhead. You don't need to do anything to unlock them other than just level up.

Great to know it should be able to be resolved one way or another, I'll just persevere for now. Thanks alot. I hope you have a great day and I look forward to seeing what you come up with. Take care for now.

**Comment by Skylin3r** [comment]
today it started giving errors, i noticed it seems to access other addon's CallbackHandler Lib
This is the error it gives with only ACP, BugSack, BugGrabber and LoadoutBindings enabled.:

2x LoadoutBindings/Modules/GUI.lua:57: attempt to index field 'GUI' (a nil value)
[string "@LoadoutBindings/Modules/GUI.lua"]:57: in function `UpdateGUI'
[string "@LoadoutBindings/Modules/Helpers.lua"]:98: in function `?'
[string "@BugSack/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@BugSack/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@BugSack/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadConfig'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:1060: in function `LoadConfigInternal'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:822: in function `SetSelectedSavedConfigID'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:249: in function `CheckSetSelectedConfigID'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:138: in function <...erSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua:135>
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:487: in function `SetUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:294: in function `ShowUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:173: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:168>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:878: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:856>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Blizzard_FrameXMLUtil/Mainline/PlayerSpellsUtil.lua"]:125: in function `TogglePlayerSpellsFrame'
[string "@Blizzard_FrameXMLUtil/Mainline/PlayerSpellsUtil.lua"]:147: in function `ToggleClassTalentOrSpecFrame'
[string "TOGGLETALENTS"]:1: in function <[string "TOGGLETALENTS"]:1>

Locals:
self = <table> {
 db = <table> {
 }
 options = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'GUI' (a nil value)"
private = <table> {
 db = <table> {
 }
 options = <table> {
 }
}

**Comment by nikkisaurus** [comment]
Try out the release [v1.3.0](https://github.com/nikkisaurus/LoadoutBindings/releases/tag/v1.3.0) and let me know if there are any more issues.

**Comment by Pokettz1** [comment]
Working perfectly now thanks! I appreciate you taking the time.
